apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    app: ai
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai
        image: luckyprice1103/tiling-ai-server:v1.5
        ports:
        - containerPort: 5000   # ✅ 컨테이너 내부에서 사용하는 포트


---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
  - port: 5000         # ✅ 쿠버네티스 서비스에서 노출하는 포트 (Frontend에서 요청 시 사용)
    targetPort: 5000   # ✅ 컨테이너 내부 포트와 일치해야 함!
  selector:
    app: ai    # ✅
  syncPolicy:
   automated:
     prune: true  # 불필요한 리소스 제거
     selfHeal: true  # 수동 변경 사항 감지하여 복구
